openapi: 3.0.0
info:
  title: Doctor Appoinment app
  version: 1.0.0
  description: documentation of doc Appoinment app
servers:
  - url: http://localhost:3000/api
tags:
  - name: Auth
    description: Api related to authentication
  - name: User
    description: Api related to user operations (authorization needed).
paths:
  "/auth/login":
    $ref: './paths/login.yaml#/schema' 
  "/auth/register":
    $ref: './paths/register.yaml#/schema' 
  "/auth/verify-otp":
    $ref: './paths/verifyOtp.yaml#/schema' 
  "/user/get-user":
    $ref: './paths/getUser.yaml#/schema' 
  "/user/profile":
    $ref: './paths/updateUser.yaml#/schema' 

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []