# swagger.yaml
openapi: 3.0.0
info:
  title: Doctor Appoinment app
  version: 1.0.0
  description: documentation of doc Appoinment app
servers:
  - url: http://localhost:3000
paths:
  /auth/login:
    post:
      summary: Login user
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Login successful
